###################################
#   ESA-SNAP mundialis base image
###################################
FROM mundialis/esa-snap:ubuntu

###################################
#   Jupyterlab setup
###################################
USER root

RUN apt-get update && \
    apt-get install -y libpq-dev && \
    apt-get clean && rm -rf var/lib/apt/lists/*

# USER $NB_UID

# RUN conda install --quiet --yes \
#     'rasterio'\
#     'geopandas' &&\
#     conda clean --all -f -y && \
#     fix-permissions "${CONDA_DIR}" && \
#     fix-permissions "/home/${NB_USER}"

# WORKDIR /src

RUN pip install jupyter -U && pip install jupyterlab

###################################
#   ESA-SNAP setup
###################################

## Move local packages to tmp file
COPY setup/requirements.txt /tmp/base_requirements.txt

# Update snap-tools
# If not running locally GitHub Actions will take care of compiling,
# only pulling the image from DockerHub is needed then
## This line results in an infinite loop, better use the .sh
# RUN /usr/local/snap/bin/snap --nosplash --nogui --modules --refresh --update-all
## When not running behind a firewall, uncomment the next two lines

# Uncomment the following lines if required to update snap
COPY setup/update_snap.sh /tmp/update_snap.sh
RUN bash /tmp/update_snap.sh

## Install requirements for python
RUN python3.6 -m pip install --upgrade pip
RUN python3.6 -m pip install --no-cache-dir --upgrade -r /tmp/base_requirements.txt

# Install snaphu
RUN wget --no-check-certificate  \
    https://web.stanford.edu/group/radar/softwareandlinks/sw/snaphu/snaphu-v2.0.5.tar.gz \
    && tar -xvf snaphu-v2.0.5.tar.gz \
    && rm snaphu-v2.0.5.tar.gz \
    && mkdir -p /usr/local/man/man1/ \
    && cd ./snaphu-v2.0.5/src \
    && make install \
    && make Clean

# Install GDAL
RUN apt-get update &&\
    apt-get install -y binutils libproj-dev gdal-bin unzip

# Update C env vars so compiler can find gdal
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

###################################
#   Miniconda installation 
###################################
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN apt-get update

RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh

RUN conda install -c conda-forge nb_conda_kernels ipykernel

###################################
#   WQP processing venv 
###################################

# Create SNAP processing env
# RUN conda create --yes -c conda-forge -n snapEnv python=3.6 gdal=2.4 rasterio \
#     requests pandas geopandas ipywidgets ipykernel lxml beautifulsoup4 selenium

COPY ./environment.yml ./environment.yml
RUN conda env create -f environment.yml

# Add the environment to the kernels of jupyterlab
# RUN python -m ipykernel install --name snapEnv --display-name "Python (snapEnv)"

# SHELL ["conda", "run", "-n", "snapEnv", "/bin/bash", "-c"]
# RUN conda init
# RUN echo 'conda activate snapEnv' >> ~/.bashrc

# TODO: setup the snappy api for using gpt from python scripts

###################################
#   WQP + snappy 
###################################

# Configuring SNAP-Python interface. 
# Reference setup
# - https://github.com/schwankner/esa-snap-with-python
# - https://senbox.atlassian.net/wiki/spaces/SNAP/pages/50855941/Configure+Python+to+use+the+SNAP-Python+snappy+interface
RUN /usr/local/snap/bin/snappy-conf /usr/bin/python3.6
RUN cd /root/.snap/snap-python/snappy/ && \
    python setup.py install
RUN ln -s /root/.snap/snap-python/snappy /root/miniconda3/envs/snapEnv/lib/python3.6/site-packages

###################################
#   WQP images analysis venv 
###################################

# # A separate environment for the image analysis is chosen for enabling the use of up-to-date libraries.

# The processing scripts for the production of the WQP are hosted in the src folder 
RUN mkdir src
WORKDIR src

# Install pygeotools, imview & demcoreg. 
# TODO: Clone the python directories for the WQP processing
# TODO: Remove unused repos
# RUN git clone https://github.com/dshean/pygeotools.git
# RUN python3.6 -m pip install -e pygeotools
# RUN git clone https://github.com/dshean/demcoreg.git
# RUN python3.6 -m pip install -e demcoreg
# RUN git clone https://github.com/dshean/imview.git
# RUN python3.6 -m pip install -e imview

# ENV PATH="src/pygeotools/pygeotools:src/demcoreg/demcoreg:src/imview/imview:$PATH"

# WORKDIR ..

# # Install xdem
# RUN git clone https://github.com/JFToro192/notebook_WQP_statistics.git
# WORKDIR ./xdem
# RUN pwd && ls
# RUN conda env create -f dev-environment.yml
# SHELL ["conda", "run", "-n", "xdem-dev", "/bin/bash", "-c"]
# RUN pip install -e .
# # TODO: avoid including additional packages using the shell command (import them from the yml file)
# RUN conda install -y -c conda-forge bmi-topography python-dotenv seaborn pysal
# RUN pip install scicomap
# RUN conda init bash

# RUN python -m ipykernel install --name snapEnv --display-name "Python (snapEnv)"
# RUN python -m ipykernel install --name xdem-dev --display-name "Python (xdem)"

###################################
#   Expose and Run Jupyter NB
###################################
SHELL ["conda", "run", "-n", "snapEnv", "/bin/bash", "-c"]
RUN conda init

WORKDIR /home/jovyan/work

EXPOSE 8888

# FIXME: Define a bash for the kernels 
ENTRYPOINT ["jupyter", "lab","--ip=0.0.0.0","--allow-root","--NotebookApp.token='jpbn'"]